# Generated by Django 4.2 on 2023-04-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='kitab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=25)),
                ('publisher', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Book_Finder',
            },
        ),
    ]
