# Generated by Django 4.2 on 2023-04-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='kitab',
            table='Book',
        ),
    ]
