# Generated by Django 4.2 on 2023-04-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0002_alter_kitab_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='kitab',
            new_name='Book',
        ),
    ]
